/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import static snake.MainProperties.GAME_SCREEN;

/**
 *
 * @author okan.uregen
 */
public class GameOver extends javax.swing.JPanel {
 GameStateManager mf;
    /**
     * Creates new form GameOver
     */
    public GameOver(GameStateManager mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(199, 243, 42));
        jToggleButton1.setForeground(new java.awt.Color(199, 243, 42));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play_again.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1);
        jToggleButton1.setBounds(470, 360, 200, 100);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Score: "+ GameScreen.tempScore*10);
        add(jLabel1);
        jLabel1.setBounds(20, 20, 250, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/game_over.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 790, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
         mf.changeScreen(GAME_SCREEN);
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
